#!/bin/bash
DIR=/root/Documents/web-server
DEPLOYDIR=/var/www/home

cp $DIR/*.html $DEPLOYDIR
cp $DIR/*.css $DEPLOYDIR
cp -r $DIR/blog $DEPLOYDIR
cp  $DIR/*.xml $DEPLOYDIR
echo "Deployed files from $DIR to $DEPLOYDIR" | tee -a ~/.deploylog


